### ISSUE TITLE
missing copyright

### ISSUE THREAD

**Issue by jgmbenoit** [grtensor/grtensor#17]
Under which license is GRTensorIII distributed ?

**Comment by grtensor** [comment]
I have not updated this. The GRTensorII source code had the following
license, which still applies.

Is licensing a concern for you?

Regards,

Peter
License:
========
GRTensor, GRTensorII, GRTensorJ and GRTensorM
are provided free of charge on the condition
that it is acknowledged that we accept no
liability for software performance, continued
maintenance, or damage to data. The authors retain
any and all rights to the software known as
GRTensor, GRTensorII, GRTensorJ and GRTensorM
their documentation and distribution. Copies of
GRTensor, GRTensorII, GRTensorJ and GRTensorM
may not be redistributed without notice to the
authors. GRTensor, GRTensorII, GRTensorJ and
GRTensorM development has been funded in part
by grants from the Natural Sciences and
Engineering Research Council of Canada (NSERC)
and the Advisory Research Committee of Queen's
University. The development of GRTensorM has
also been supported by a Visiting Scholar Grant
to Peter Musgrave from Wolfram Research.

**Comment by grtensor** [comment]
Added license file from GRII to GRIII
2.1.9 Sept 24, 2017
