### ISSUE TITLE
Please allow to set all grOptions before invoking grtensor

### ISSUE THREAD

**Issue by jgmbenoit** [grtensor/grtensor#19]
It appears that some grOptions can be set before invoking grtensor but not all.
For example, grOptionMetricPath  and grOptionqloadPath can be set before while grOptionWindows cannot. It would be nice, if not consistent, to be able to set all the grOptions before.

**Comment by grtensor** [comment]
Good point. 

Global init now first checks to see if there is a value from the init file. 

Fix in 2.1.7
