### ISSUE TITLE
Please provide the full source

### ISSUE THREAD

**Issue by jgmbenoit** [grtensor/grtensor#20]
Do you have any reason to not provide the all source in such a way that we can build our own MLA, and more importantly, to pull patches.

**Comment by grtensor** [comment]
The source is available at https://github.com/grtensor/grtensor3src

This repo (grtensor/grtensor) represents the "release" bundle.

**Comment by jgmbenoit** [comment]
Thanks for your prompt reply and very sorry for the confusion,
