### ISSUE TITLE
package doesn't load on Maple15/MacOS

### ISSUE THREAD

**Issue by samrocha** [grtensor/grtensor#21]
I get the following:
> with(grtensor);
print(`output redirected...`); # input placeholder
Error, Got internal error in grtensor:-grinit : "at offset 8143 in `:-2257.m`, unexpected DAG type: 0,122,(z)"

At this point I have no grinit nor mapleinit.

I'd appreciate any help, or else, going back to grii.

**Comment by grtensor** [comment]
Hi, 

This error has also been reported on Maple 16. I believe that the issue is that earlier versions of Maple cannot read the library format of more recent packaging. 

Unfortunately, you'll need to stay with grii.

**Comment by samrocha** [comment]
Ok. Thanks anyway.

Samuel Rocha de Oliveira
IMECC - UNICAMP
