### ISSUE TITLE
grdef error

### ISSUE THREAD

**Issue by ghost** [grtensor/grtensor#33]
I cannot define any new tensor.  The error is " invalid PROC length
Error, (in procmake/tomaple) assembled object is invalid "
I'm using maple 13 and grtensorII.

**Comment by grtensor** [comment]
The error message matches that from Issue #30 

I am not sure what version grtensor5 refers to. Is this the latest (2.2)?

I do not have access to Maple 13, so I am not able to debug directly. There have been changes in how some elements in procmake work (specifically the number of arguments for _inert_For changed going from Maple 2017 to Maple 2018). This might be a related issue.
