### ISSUE TITLE
Asking to load a metric, although it is not required

### ISSUE THREAD

**Issue by chinthakmurali** [grtensor/grtensor#35]
I am trying to calculate the independent components of a six rank tensor, using its symmetries. But when I use grcalc command, it is asking me to load a metric, even though I am just counting the independent components of the tensor, it has nothing to do with the metric.

**Comment by nbodyphysics** [comment]
GRTensorIII is a package for component calculations for a specific metric or metrics. It was not designed to do indicial calculations. Consequently it will always require a metric. 

Unfortunately GRTensorIII is not the appropriate package for your calculation.

**Comment by chinthakmurali** [comment]
Thank you so much for the response.  So, can I use GRTensor II instead,  for my calculation?

**Comment by nbodyphysics** [comment]
No, GRTensorII has the same premise. 

The best recent survey of software I am aware of is:
https://link.springer.com/content/pdf/10.1007%2Fs41114-018-0015-6.pdf
