### ISSUE TITLE
Does GrTensor work with maple 2019?

### ISSUE THREAD

**Issue by ouboub** [grtensor/grtensor#36]
Hi

I just installed maple 2019 on my linux machine (running Ubuntu 16.04), I followed the steps indictaed in the README file and everyting seemed fine, I loaded the path, started GRtensor, and then I wanted to open an example file found the metrics directory, 
maple crashed.
I have to admit that I am new to maple (I am a matlab user) but crashing can never be good.
so what is the state of art with maple 2019

thanks and regards

Uwe Brauer

**Comment by grtensor** [comment]
Hi Uwe,

It seems really odd that GRTensor could do something to crash Maple. What
file did you open?

Generally the metrics are not worksheet files (.ms) to be opened but from
the "old" approach where metrics were loaded by grload(). This does still
work and you can use grload() with no argument to get a file chooser. I
prefer these days to use the spacetime() command, since then the metric is
defined in the worksheet and there can be no confusion or migration issues.

Are you able to use e.g.
https://github.com/grtensor/grtensor/blob/master/worksheets/intros/intro_book.mw
?

Regards,

Peter

**Comment by ouboub** [comment]
HI Peter 

thanks for the quick reply. Indeed I can open, without any trouble or crash the intro_book.nw, at first
but then after a few seconds it crashed with the same gtk-qt-engine pop up window I have seen again.

BTW I forget to tell you, when I load the library there is the following error:
s=0x7f0986dab428, LENGTH=7, invalid FOR length

"GRTensor has detected correct length for inert FOR. Disregard 

   the above error"
                "

                  GRTensor III v2.2 Oct 1, 2018"
So I am not sure what to conclude from the above error message, but yep, maple crashes. My university also has the 2018 version (but it took me some time to install the 2019 version, so I am not too keen to rerun the installation for 2018)
regards

Uwe

**Comment by grtensor** [comment]
The FOR length error is an awkward but deliberate startup message (does a
try/catch to check to see what length of FOR function maple supports). I
need to find a better way to do that.

All I can think of is that there is some backward compatibility issue with
a Maple worksheet. I forget if the examples were saved in Maple 2017 or
Maple 2018. I'd guess 2017.

If you run GRIII commands in a new worksheet does it still crash? e.g.
following an example in the docs.

I'll poke around a bit in a day or two and see if I can reproduce this
issue.

Peter

**Comment by ouboub** [comment]
> If you run GRIII commands in a new worksheet does it still crash? e.g. following an example in the docs.
I will try this out and report back
Uwe

**Comment by grtensor** [comment]
I now have a copy of Maple 2019 and do not see the issue you are reporting.
(I am using a PC).

I also have another user who has it running on 2019 (version 2.2 is
required, but even with an older version it does not crash).

Regards,

Peter

**Comment by ouboub** [comment]
Hm, 
ok, I will test it again later today and see what happens. You say you use a PC, do you mean MS Windows? Could that make a difference? I am running Linux and my feeling was that the LInux version of Maple is a bit buggier than the MS Windows version.

regards

Uwe

**Comment by grtensor** [comment]
It could be a Linux thing. What Linux are you using? I have another license
and I could setup a Vm to try it out.


Peter

**Comment by ouboub** [comment]
Hi Peter

sorry for the delay, but I had to travel. Now I am back (using Ubuntu 16.04) I started maple and could 
open without any problems
https://github.com/grtensor/grtensor/blob/master/worksheets/intros/intro_book.mw

any suggestions for running some tests?

I am now a bit puzzled.

Uwe

**Comment by grtensor** [comment]
Hi,

I have maple2019 on Ubuntu (18.04.2).

I can load GRTensorIII and use e.g. grload() to load the rnds metric and
the calculate G(up,dn).

Are you able to recreate your crash? Can you remind of what the sequence
was to cause it?

Thanks,

Peter

**Comment by ouboub** [comment]
Hi Peter

I am not able to reproduce the crash at the moment. Just to be sure could you please tell me which document you open (I can't find it in the metric directory) do you mean GRTensorIII.html.

are you then loading the rnds metric manually (typing) or via the mouse and copying. Sorry for this elementary question.

thanks

Uwe

**Comment by grtensor** [comment]
I just started a new worksheet and used grload();

When used with no argument it provides a file chooser. I then navigated the
the grtensor/metrics directory and selected rnds.mpl and did
grcalcd(G(up,dn));

P

**Comment by ouboub** [comment]
Sorry I cannot follow.

> I just started a new worksheet and used grload(); 
done
> When used with no argument it provides a file chooser. I
not in my case.

So I open rnds.mpl in the grtensor/metrics
and I run  grcalcd(G(up,dn))

I obtain the following screen which I attach.

Uwe

![maple-result](https://user-images.githubusercontent.com/5957203/62836601-292c5200-bc65-11e9-9e48-064b54a48934.png)

**Comment by grtensor** [comment]
Hmm. Was GRTensorIII loaded first? I set up the libname path, did
with(grtensor) and then did a grload();

If so, was there any output from running grload()?

The metric files are just flay files that define the metric elements. They
are not intended to be loaded directly.

Peter

**Comment by abeesham** [comment]
Hi, I am trying grtensor III with maple 2020. When I try grload(); and try to calculate (up,dn), this is the error message:

"grload();
Loading as schw from C:\grtensor-master\metrics\schw.mplCalculated ds for schw (0.000000 sec.)

                    Default spacetime = schw

                    For the schw spacetime:

                          Coordinates

                             x(up)

                      a                     
                    x   = [r, theta, phi, t]

                          Line element

               2                                            
       2    d r       2         2     2           2       2 
     ds  = ------- + r   d theta   + r  sin(theta)   d phi  
               2 m                                          
           1 - ---                                          
                r                                           

         /     2 m\     2 
       + |-1 + ---|  d t  
         \      r /       


       The Schwarzschild metric in curvature coordinates

grcalcd(g(up, dn));
Calculated detg for schw (0.000000 sec.)
Calculated g(up,up) for schw (0.015000 sec.)

Error, (in grtensor:-grcalc) Internal error-symmetry function did not return NULL, grG_ObjDef[g(up, dn)][grC_symmetry]
grcalcd(G(up, dn));
s=000001EAF8A6D070, LENGTH=7, invalid FOR length

Error, (in procmake/tomaple) assembled object is invalid"

Can you help?

Aroon

**Comment by grtensor** [comment]
Hi,

I suspect you need a newer version of GRIII from
https://github.com/grtensor/grtensor.

If the problem persists please let me know.

Regards,

Peter

**Comment by abeesham** [comment]
I downloaded GRIII from github a few days ago

**Comment by grtensor** [comment]
Strange.

I just updated my Maple 2020 and did not see an issue like this.

Can you please send your test worksheet with output and the specific
version of Maple to grtensor3@gmail.com? Also, is this PC, Mac or Linux?

Thx, P

**Comment by abeesham** [comment]
Dear Peter
Have you had a chance to look at this issue yet?
Regards

Aroon Beesham, Tel: +27-(0)76-274-8833 (cell) 

    On Tuesday, July 28, 2020, 9:27:35 PM GMT+2, grtensor <notifications@github.com> wrote:  
 
 

Strange.

I just updated my Maple 2020 and did not see an issue like this.

Can you please send your test worksheet with output and the specific
version of Maple to grtensor3@gmail.com? Also, is this PC, Mac or Linux?

Thx, P
