### ISSUE TITLE
How to assign value to components of a tensor defined using grdef

### ISSUE THREAD

**Issue by AnishAgashe** [grtensor/grtensor#37]
Hello,

I am using GRTensorIII for some symbolic calculations involving tensors and I am facing the following issue:

After I define a tensor using grdef, e.g. grdef(T(^a b c d)), I can't seem to find a command to assign values to the individual components of this tensor. When I use grcalc, the program asks to input the values for components manually one by one, which is impractical if you have a tensor with (4^4) 256 components.

I may be missing something very basic here, and I appreciate any help.

Thanks
--
Anish

**Comment by gdreid** [comment]
You want to use kdelta in the define to access the individual tensor
components. Multiplying those by the relevant component gives you component
level access.

**Comment by grtensor** [comment]
kdelta is a fine idea.

There is an undocumented test function that is handy (and I should
document). grtestinput(). It takes a list of entries and uses them for the
next set of input prompts. I use it in regression testing.

Attached is a quick example.

Peter

**Comment by AnishAgashe** [comment]
Thank you so much for the quick replies. I will try both the suggestions and let you know if it resolved the issue.

@grtensor 
It does not seem that there is any example attached with your message. Could you please send that again?

Thanks
Anish

**Comment by AnishAgashe** [comment]
@grtensor 

Sorry to bother you again, can you please attach the example you mentioned in your message?

Thanks
--
Anish

**Comment by grtensor** [comment]
Sure.

**Comment by AnishAgashe** [comment]
Somehow, I am not able to see any attachment. Can you please e-mail it to anish.agashe@utdallas.edu

Thanks

**Comment by AnishAgashe** [comment]
**grtestinput()** does not seem to solve the difficulty I was having. If you remember, there was a function **setcmpt()** in grtensorII, which seems to be not there in grtensorIII anymore (correct me if I am mistaken). Is there anything equivalent to **setcmpt()** that is available in grtensorIII?

Thanks

**Comment by grtensor** [comment]
Ah, I see Denis added that in 1999.

I did convert the code when I updated GRIII but did not make it public. Let
me build a version with it made public and see if it does what it used to
do.

**Comment by grtensor** [comment]
I have made the function public and pushed the change up to github. Version
2.4 May 19, 2020.

I did a quick sanity check (set several components on Riemann) that worked.
Please let me know if you see anything odd.

**Comment by AnishAgashe** [comment]
Thanks a lot. It is working as desired. This seems to have solved the problem I was having.

Thank you for all your help.
--
Anish
