### ISSUE TITLE
grtransform

### ISSUE THREAD

**Issue by cmbant** [grtensor/grtensor#40]
Doing for example
`
grtransform(schw, schw2, [rp(r) = r, thetap(theta) = theta, phip(phi) = phi, tp(t) = t])`

results in a metric that's a function of both the new and old coordinates using Maple 2019 latest. Then, for example, all the Christoffels are zero. Surely the result should only be a function of the new coordinates? (or the documentation is very unclear)

**Comment by grtensor** [comment]
Yep, sounds like a bug. I'll take a look this week.

**Comment by grtensor** [comment]
Looking at the example https://github.com/grtensor/grtensor/blob/master/worksheets/intros/Schw_to_KS_Carroll_eqn5_120.mw
the substitution of the co-ordinate transform is done explicitly using subs with grmap

i.e.
grmap(g(dn, dn), subs, r = r(R, T), 'x')

Looking at the code for grtransform it does not do any substitutions. 

I will make this explicit by adding a warning to the grtransform output:
"NOTE: still need to apply coordinate transforms to metric to finish the job using grmap with subs"
