### ISSUE TITLE
grtensor and Maple 2021

### ISSUE THREAD

**Issue by MaxBanados** [grtensor/grtensor#42]
I am problems running grtensor3 on Maple 21. (I have used grtensorII  for years on earlier versions of Maple with no problem. But far the best GR program ever built!)

I have installed grtensor and it is running. I can run the demo, for example. 

But:
-- when I define new objects (via grdef) and compute something via (grcalc;grdisplay) I get a not understandable result
![image](https://user-images.githubusercontent.com/84876920/119728436-7af59a80-be41-11eb-8b8e-80d69b8ff79f.png)

-- Also  on startup I get the message 
s=000002D3F8366188, LENGTH=7, invalid FOR length
which other people seem to get as well. 

Any help?   Thanks!

**Comment by grtensor** [comment]
Just to confirm, are you using Maple 2021 ? (Maple did once use two- digit
versions up to 18, I think).

Peter

**Comment by MaxBanados** [comment]
thanks for your quick reply!   this is the version. Sorry I am in rush right now... 




On 26-May-21 4:56:55 PM, grtensor ***@***.***> wrote:
Just to confirm, are you using Maple 2021 ? (Maple did once use two- digit
versions up to 18, I think).

Peter

**Comment by grtensor** [comment]
Ok. Let me get a copy of 2021 (I have only previously tried an early beta)
and see if I can reproduce.

Hopefully I'll  have that in place tomorrow.

Peter

**Comment by MaxBanados** [comment]
Thank you for your quick reply! 

I attach to this email a sample file. In the last line you will see the unwanted output. 

This problem happens only with new objects. I have played with combinations of predefined 
tensor and everything seems alright. 

I would love to have grtensor3 running on my new Maple! 

Thank you,
Max

On 26-May-21 5:14:56 PM, grtensor ***@***.***> wrote:
Ok. Let me get a copy of 2021 (I have only previously tried an early beta)
and see if I can reproduce.

Hopefully I'll have that in place tomorrow.

Peter

**Comment by grtensor** [comment]
My grdef testcases are working in Maple 2021.  I'm using GRIII version:
"GRTensor III v2.5 Oct 2, 2020"

Can you please email a copy of the work sheet that has issues to grtensor3@gmail.com? I can try it and see I can duplicate the error. 

Thx, Peter

**Comment by MaxBanados** [comment]
Dear Peter,
I attach a worksheet with the problem. 
I include two calculations one with the problem and 
one without.

I am not sure which version of grtensor I have. 
I downloaded it from github a few days ago.
I guess it is the latest one. 

Thank you for your help!
Max




On 27-May-21 5:43:13 AM, grtensor ***@***.***> wrote:
My grdef testcases are working in Maple 2021. I'm using GRIII version:
"GRTensor III v2.5 Oct 2, 2020"
Can you please email a copy of the work sheet that has issues to ***@***.*** ***@***.***? I can try it and see I can duplicate the error.
Thx, Peter
