### ISSUE TITLE
Not working on maple 2021

### ISSUE THREAD

**Issue by shobhitsachan** [grtensor/grtensor#43]
![image](https://user-images.githubusercontent.com/53273856/131284510-4049d7f8-b7ca-43f7-9e54-650642d7163e.png)

While running the grtensorIII on Maple 2021, I am encountering the error as shown in the attachment. Everything is fine while using Maple 2017.
 So some of you have the solutions. Please let me know the solution.

Thanks
@shobhitsachan

**Comment by grtensor** [comment]
Hi,

Please update to the latest GRIII from https://github.com/grtensor/grtensor.
I believe this will resolve the issue.

Regards,
Peter
