### ISSUE TITLE
saving objects

### ISSUE THREAD

**Issue by MaxBanados** [grtensor/grtensor#44]
I am missing in GrtensorIII the command grsaveobj which I used a lot with GrtensorII.

Is there an alternative command?

I have a defined a long object (giving its components one by one, in one session),
and would like to load it from a file in the following sessions. 

Thanks! 
Max

**Comment by grtensor** [comment]
Hi Max,

Yes, there is an alternative approach to this. There is a command
grtestinput which "preloads" answers to the interactive prompts to specify
an object component by component. An example is attached. This then allows
the definition to be copied from worksheet to worksheet without trying to
write info to files etc.

I have been meaning to add this to the docs.

Regards,

Peter

**Comment by MaxBanados** [comment]
Dear Peter, thanks for your quick reply. I did not see any attachments though. 
Can you post the example again? Thanks, 
Max

**Comment by grtensor** [comment]
Curious. I see the attachment in my reply. Maybe because it is a .mw and
your mailer thought it was malware?

Here is a PDF.

P

**Comment by MaxBanados** [comment]
I don't see the pdf either!  I tried it on my email client *and* the GitHub platform, no luck. Perhaps you can email me directly to maxbanados at gmail.com  ?   Thanks, Max
