### ISSUE TITLE
GRJunction

### ISSUE THREAD

**Issue by AnishAgashe** [grtensor/grtensor#45]
Hello,

I apologise if this is not the right place to ask this. I was wondering if GRJunction is still available. I could not find it on the old website -- the page for GRJunction does not load.
Any help is appreciated.

Thanks
--
Anish

**Comment by grtensor** [comment]
Hi, 

Fair question. I really need to update the docs….

Junction is now built in to GRIII. I can see some example worksheets in junction <https://github.com/grtensor/grtensor3src/tree/master/worksheets/junction> but I have not used it in five years. I’m pretty sure I left it in working condition. 

Regards, 

Peter

**Comment by AnishAgashe** [comment]
Thanks for the quick reply. I will check the example worksheets out.

Regards
--
Anish
